import type { Locale } from './i18n'

// Localized versions of the existing prototype copy, used only when CMS content is missing.
const bhs: Record<string, string> = {
  'Solutions': 'Rješenja',
  'Projects': 'Projekti',
  'Capabilities': 'Mogućnosti',
  'About': 'O nama',
  'Stories': 'Priče',
  'Resources': 'Resursi',
  'Contact': 'Kontakt',
  'START A PROJECT': 'POKRENIMO PROJEKAT',
  'Start a Project': 'Pokrenimo projekat',
  'Skip to content': 'Pređi na sadržaj',
  'Dev Studio home': 'Dev Studio početna',
  'Dev Studio back to top': 'Dev Studio povratak na vrh',
  'Main navigation': 'Glavna navigacija',
  'CLOSE −': 'ZATVORI −',
  'MENU +': 'MENI +',
  'Smart Retail': 'Pametna maloprodaja',
  'Interactive Systems': 'Interaktivni sistemi',
  'Brand Experiences': 'Brend iskustva',
  'DIGITAL MEETS PHYSICAL': 'SPOJ DIGITALNOG I FIZIČKOG',
  'TECHNOLOGY YOU CAN TOUCH': 'TEHNOLOGIJA KOJU MOŽETE DODIRNUTI',
  'IDEAS WITH A PHYSICAL PRESENCE': 'IDEJE U FIZIČKOM OBLIKU',
  'AN ORIGINAL DEV STUDIO PRODUCT': 'ORIGINALNI DEV STUDIO PROIZVOD',
  'Exploring the space between a digital interface and a physical retail experience.': 'Istražujemo prostor između digitalnog interfejsa i fizičkog iskustva kupovine.',
  'Interfaces, electronics and enclosures considered together as one complete system.': 'Interfejsi, elektronika i kućišta osmišljeni zajedno kao jedan cjelovit sistem.',
  'A space for expressive installations and memorable physical interactions.': 'Prostor za upečatljive instalacije i fizičke interakcije koje se pamte.',
  'Our own product, Kids Play. Product photography and the full story will be added in the content phase.': 'Naš proizvod, Kids Play. Fotografije proizvoda i cijela priča biće dodani u fazi pripreme sadržaja.',
  'Concept': 'Koncept',
  'Design & Engineering': 'Dizajn i inženjering',
  'Hardware + Software': 'Hardver + softver',
  'Production': 'Proizvodnja',
  'Installation': 'Instalacija',
  'Find the right problem. Shape the idea. Define what the product needs to become.': 'Pronaći pravi problem. Oblikovati ideju. Definisati šta proizvod treba da postane.',
  'Turn intent into form, materials, mechanics and a plan that can be built.': 'Pretvoriti zamisao u oblik, materijale, mehaniku i plan koji se može realizovati.',
  'Make the physical and digital work together, from electronics to the interface.': 'Povezati fizičko i digitalno, od elektronike do interfejsa.',
  'Bring the design off the screen and into the workshop. Manufacture, assemble and refine.': 'Prenijeti dizajn sa ekrana u radionicu. Proizvesti, sastaviti i usavršiti.',
  'Bring every part together in its real environment, with support beyond delivery.': 'Povezati sve dijelove u stvarnom okruženju, uz podršku i nakon isporuke.',
  'Behind the Build': 'Iza izrade',
  'The thinking behind the making.': 'Razmišljanje iza stvaranja.',
  'Technology': 'Tehnologija',
  'Where hardware meets software.': 'Gdje se hardver susreće sa softverom.',
  'Studio Notes': 'Bilješke iz studija',
  'Ideas are only the beginning.': 'Ideje su tek početak.',
  'INDEPENDENT THINKING. INTEGRATED MAKING.': 'NEZAVISNO RAZMIŠLJANJE. POVEZANO STVARANJE.',
  'FROM IDEA TO REALITY.': 'OD IDEJE DO STVARNOSTI.',
  'WE BUILD': 'GRADIMO',
  'WHAT OTHERS': 'ONO ŠTO DRUGI',
  'ONLY IMAGINE.': 'TEK ZAMIŠLJAJU.',
  'Design. Electronics. Software. Manufacturing.': 'Dizajn. Elektronika. Softver. Proizvodnja.',
  'From the first idea to a finished product — engineered, built and delivered by one team.': 'Od prve ideje do gotovog proizvoda — jedan tim za razvoj, izradu i isporuku.',
  'Explore our work': 'Istražite naš rad',
  'IDEAS ARE JUST THE BEGINNING.': 'IDEJE SU TEK POČETAK.',
  'SCROLL TO DISCOVER ↓': 'SKROLUJTE I OTKRIJTE ↓',
  'DESIGN × ENGINEERING × PRODUCTION': 'DIZAJN × INŽENJERING × PROIZVODNJA',
  '01 / THE STUDIO': '01 / STUDIO',
  'ONE TEAM.': 'JEDAN TIM.',
  'EVERY DISCIPLINE REQUIRED': 'SVE POTREBNE DISCIPLINE',
  'TO BUILD THE ENTIRE PRODUCT.': 'ZA IZRADU CIJELOG PROIZVODA.',
  'Industrial design, electronics, software, manufacturing and installation. Different disciplines, working at the same table. We connect every part of the process to turn ambitious ideas into things that exist.': 'Industrijski dizajn, elektronika, softver, proizvodnja i instalacija. Različite discipline za istim stolom. Povezujemo svaki dio procesa da ambiciozne ideje pretvorimo u stvari koje postoje.',
  'Meet the one-team advantage': 'Upoznajte prednost jednog tima',
  '02 / SELECTED DIRECTIONS': '02 / ODABRANI PRAVCI',
  'PHYSICAL. DIGITAL. EVERYTHING BETWEEN.': 'FIZIČKO. DIGITALNO. SVE IZMEĐU.',
  'IDEAS.': 'IDEJE.',
  'MADE TANGIBLE.': 'U OPIPLJIVOM OBLIKU.',
  'A first look at the worlds we build in.': 'Prvi pogled na svjetove u kojima stvaramo.',
  'Visual studies for the projects to come.': 'Vizuelne studije za buduće projekte.',
  'VIEW STUDY ↗': 'POGLEDAJTE STUDIJU ↗',
  '03 / WHAT WE BUILD': '03 / ŠTA GRADIMO',
  'NO SINGLE DISCIPLINE. NO SINGLE BOX.': 'BEZ GRANICA JEDNE DISCIPLINE.',
  'COMPLEX IDEAS.': 'SLOŽENE IDEJE.',
  'COMPLETE': 'CJELOVITA',
  'SOLUTIONS.': 'RJEŠENJA.',
  'Retail Technology': 'Maloprodajna tehnologija',
  'Custom Products': 'Proizvodi po mjeri',
  'Entertainment': 'Zabava',
  'Manufacturing': 'Proizvodnja',
  '04 / FROM FIRST THOUGHT TO FINAL DETAIL': '04 / OD PRVE MISLI DO ZAVRŠNOG DETALJA',
  'ONE CONTINUOUS PROCESS': 'JEDAN POVEZAN PROCES',
  'YOU BRING THE IDEA.': 'VI DONOSITE IDEJU.',
  'WE MAKE': 'MI JE ČINIMO',
  'IT': '',
  'REAL.': 'STVARNOM.',
  'Every decision moves the product forward.': 'Svaka odluka unapređuje proizvod.',
  'Every discipline stays connected.': 'Sve discipline ostaju povezane.',
  'WE DELIVER THE PRODUCT.': 'MI ISPORUČUJEMO PROIZVOD.',
  '05 / THE ONE-TEAM ADVANTAGE': '05 / PREDNOST JEDNOG TIMA',
  'LESS DISTANCE BETWEEN IDEA AND REALITY.': 'KRAĆI PUT OD IDEJE DO STVARNOSTI.',
  'NO HANDOFF': 'BEZ PREDAJE',
  'BETWEEN FIVE': 'IZMEĐU PET',
  'COMPANIES.': 'KOMPANIJA.',
  'One conversation that continues from concept to installation. Designers talk to engineers. Software meets hardware. Production informs the design. The knowledge stays with the team, and the team stays with the product.': 'Jedan razgovor koji traje od koncepta do instalacije. Dizajneri razgovaraju sa inženjerima. Softver susreće hardver. Proizvodnja usmjerava dizajn. Znanje ostaje u timu, a tim ostaje uz proizvod.',
  'See where it comes together': 'Pogledajte gdje sve nastaje',
  'MATERIAL / MECHANICS / MAKING': 'MATERIJALI / MEHANIKA / IZRADA',
  '06 / MADE HERE': '06 / PROIZVEDENO OVDJE',
  'DESIGNED HERE.': 'OSMIŠLJENO OVDJE.',
  'ENGINEERED HERE.': 'RAZVIJENO OVDJE.',
  'BUILT HERE.': 'IZRAĐENO OVDJE.',
  'Close to the materials. Close to the machines. Close to every decision that makes the final product better.': 'Blizu materijala. Blizu mašina. Blizu svake odluke koja konačni proizvod čini boljim.',
  'Banja Luka, Bosnia & Herzegovina': 'Banja Luka, Bosna i Hercegovina',
  'INDUSTRIAL FORM STUDY / WORKSHOP MEDIA TO FOLLOW': 'STUDIJA INDUSTRIJSKE FORME / SNIMCI RADIONICE USKORO',
  '07 / OUR OWN IDEAS, OUT IN THE WORLD': '07 / NAŠE IDEJE U STVARNOM SVIJETU',
  'DEV STUDIO ORIGINALS': 'DEV STUDIO ORIGINALI',
  'WE DON’T ONLY BUILD FOR CLIENTS.': 'NE GRADIMO SAMO ZA KLIJENTE.',
  'WE BUILD OUR OWN PRODUCTS.': 'GRADIMO I VLASTITE PROIZVODE.',
  'IMAGINED AND DEVELOPED BY DEV STUDIO': 'OSMISLIO I RAZVIO DEV STUDIO',
  'A little more': 'Malo više',
  'room for': 'prostora za',
  'play.': 'igru.',
  'Kids Play is an original Dev Studio product. The same integrated thinking, applied to an idea of our own.': 'Kids Play je originalni Dev Studio proizvod. Isti povezani pristup, primijenjen na našu vlastitu ideju.',
  'An original Dev Studio product. This visual explores a playful design direction; product details and real photography will follow.': 'Originalni Dev Studio proizvod. Ovaj vizuelni prikaz istražuje razigrani dizajnerski pravac; detalji proizvoda i stvarne fotografije slijede.',
  'Discover Kids Play': 'Otkrijte Kids Play',
  '08 / LATEST FROM THE STUDIO': '08 / NOVOSTI IZ STUDIJA',
  'WORK IN PROGRESS. THINKING IN MOTION.': 'RAD U TOKU. MISLI U POKRETU.',
  'INSIDE': 'IZA',
  'THE MAKING.': 'STVARANJA.',
  'EDITORIAL PREVIEWS / STORIES COMING SOON': 'NAJAVE SADRŽAJA / PRIČE USKORO',
  'PREVIEW': 'NAJAVA',
  'THE NEXT THING WE BUILD COULD BE YOURS.': 'SLJEDEĆE ŠTO IZGRADIMO MOŽE BITI VAŠE.',
  'LET’S TALK.': 'RAZGOVARAJMO.',
  'GOT AN IDEA?': 'IMATE IDEJU?',
  'LET’S BUILD IT.': 'IZGRADIMO JE.',
  'BACK TO TOP ↑': 'NA VRH ↑',
  'Close panel': 'Zatvori panel',
  'CLOSE ×': 'ZATVORI ×',
  'DEV STUDIO / DESIGN PREVIEW': 'DEV STUDIO / PREGLED DIZAJNA',
  'Visit the current website': 'Posjetite trenutni sajt',
  'Let’s start with your idea.': 'Počnimo od vaše ideje.',
  'The project enquiry form is coming next. This design prototype does not collect or send information. Visit the current Dev Studio website to get in touch.': 'Obrazac za projektni upit stiže uskoro. Ovaj prototip dizajna ne prikuplja niti šalje podatke. Za kontakt posjetite trenutni Dev Studio sajt.',
  'The details. All in one place.': 'Detalji. Sve na jednom mjestu.',
  'The Dev Studio catalog, product flyers and thematic brochures will be available here in BHS and English. Download files have not been added to this prototype.': 'Dev Studio katalog, flajeri proizvoda i tematske brošure biće dostupni ovdje na BHS i engleskom jeziku. Datoteke za preuzimanje još nisu dodane u ovaj prototip.',
}

export function homeText(locale: Locale, text: string): string {
  return locale === 'bhs' ? bhs[text] ?? text : text
}
